[package]
edition = "2021"
name = "simple"
version = "0.1.0"

[dependencies]
futures = "0.3.18"
task-tracker = {path = "../.."}
tokio = {version = "1", features = ["rt", "macros"]}
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
